export const FETCH_INFO = 'FETCH_INFO';
export const FETCH_USER_INFO = 'FETCH_USER_INFO';
export const FETCH_LESSON_INFO = 'FETCH_LESSON_INFO';
export const FETCH_STUDENT_LIST = 'FETCH_STUDENT_LIST';
export const FETCH_CLASS_INFO = 'FETCH_CLASS_INFO';
export const FETCH_SATISFILED_LIST = 'FETCH_SATISFILED_LIST';
export const GET_CURRENT_UNREVIEW= 'GET_CURRENT_UNREVIEW';
export const GET_CURRENT_REVIEW= 'GET_CURRENT_REVIEW';
export const GET_ALL_UNREVIEW= 'GET_ALL_UNREVIEW';
export const GET_ALL_REVIEW= 'GET_ALL_REVIEW';
export const SEARCH_STUDENT = 'SEARCH_STUDENT';
export const CHANGE_SATISFILED = 'CHANGE_SATISFILED';
export const SHOW_POPOVER = 'SHOW_POPOVER';
export const HIDE_POPOVER= 'HIDE_POPOVER';
export const REVIEW_HOMWWORK= 'REVIEW_HOMWWORK';


