export const Show_ChangeDialog = 'Show_ChangeDialog'
export const Show_AddDialog = 'Show_AddDialog'
export const Close_Dialog = 'Close_Dialog'
export const Show_MulSelect = 'Show_MulSelect'
export const Put_CurrrentIndex =  'Put_CurrrentIndex'
export const Add_Item = 'Add_Item'
export const Top_Item = 'Top_Item'
export const Delete_Item = 'Delete_Item'
export const Delete_MoreItem = 'Delete_MoreItem'
export const Push_DeleteItem = 'Push_DeleteItem'
export const Splice_DeleteItem = 'Splice_DeleteItem'

