export const FETCH_INFO = 'FETCH_INFO';
export const FETCH_USER_INFO = 'FETCH_USER_INFO';
export const FETCH_LESSON_INFO = 'FETCH_LESSON_INFO';
export const FETCH_STUDENT_LIST = 'FETCH_STUDENT_LIST';
export const FETCH_CLASS_INFO = 'FETCH_CLASS_INFO';
export const SEARCH_STUDENT = 'SEARCH_STUDENT';

