export const FETCH_INFO = 'FETCH_INFO';
export const FETCH_USER_INFO = 'FETCH_USER_INFO';
export const FETCH_LESSON_INFO = 'FETCH_LESSON_INFO';
export const FETCH_STUDENT_LIST = 'FETCH_STUDENT_LIST';
export const FETCH_CLASS_INFO = 'FETCH_CLASS_INFO';
export const FETCH_SATISFILED_LIST = 'FETCH_SATISFILED_LIST';
export const GET_CURRENT_UNREVIEW= 'GET_CURRENT_UNREVIEW';
export const GET_CURRENT_REVIEW= 'GET_CURRENT_REVIEW';
export const GET_ALL_UNREVIEW= 'GET_ALL_UNREVIEW';
export const GET_ALL_REVIEW= 'GET_ALL_REVIEW';
export const SEARCH_STUDENT = 'SEARCH_STUDENT';
export const CHANGE_SATISFILED = 'CHANGE_SATISFILED';
export const SHOW_POPOVER = 'SHOW_POPOVER';
export const HIDE_POPOVER= 'HIDE_POPOVER';
export const REVIEW_HOMWWORK= 'REVIEW_HOMWWORK';
export const REVIEW_REJECT= 'REVIEW_REJECT';
export const SEARCH_HOMEWORK= 'SEARCH_HOMEWORK';
export const CHANGE_EXCELLENT= 'CHANGE_EXCELLENT';
export const CHANGE_CURRENT_SELECT= 'CHANGE_CURRENT_SELECT';
export const CHANGE_POWER_TYPE= 'CHANGE_POWER_TYPE';
export const SHOW_CONFIG= 'SHOW_CONFIG';;
export const FILTER_HANDLE_RESULT= 'FILTER_HANDLE_RESULT';
export const FILTER_HANDLE_LOAD= 'FILTER_HANDLE_LOAD'
export const ADD_PERSON= 'ADD_PERSON'
export const DELETE_PERSON= 'DELETE_PERSON'
export const DELETE_FLAG= 'DELETE_FLAG'
export const ADD_SELECT= 'ADD_SELECT'
export const DELETE_SELECT= 'DELETE_SELECT'
export const ADD_DELETE_SELECT= 'ADD_DELETE_SELECT'
export const DELETE_DELETE_SELECT= 'DELETE_DELETE_SELECT'







